name: caller-workflow
# Trigger condition can be update per your preference
on:
  workflow_call:
  push:
  pull_request:

jobs:
  caller-workflow:
    runs-on: ubuntu-latest 
    steps:
      - name: output
        run: |
          echo "hello world!"

